import { rename, writeFile, access } from "node:fs/promises";
import { fileURLToPath } from "node:url";

/**
 * Build-time export merge (§15, the one-Worker recipe). adapter-cloudflare v7
 * emits a default-export-only `_worker.js`; the Cloudflare runtime needs the
 * Durable Object classes as NAMED exports at the top of the deployed bundle.
 * So after `vite build` we rename the adapter's worker aside and write a tiny
 * `_worker.js` that re-exports its default (the SvelteKit fetch handler) PLUS
 * the DO classes. `main` in wrangler.jsonc points here; wrangler bundles it,
 * pulling the SvelteKit worker + the DOs (+ automerge) into one script.
 */
const dir = fileURLToPath(new URL("../.svelte-kit/cloudflare/", import.meta.url));
const adapterWorker = `${dir}_worker.js`;
const sveltekitWorker = `${dir}_sveltekit_worker.js`;

try {
  await access(adapterWorker);
} catch {
  console.error(`[merge-worker] ${adapterWorker} not found — run \`vite build\` first.`);
  process.exit(1);
}

await rename(adapterWorker, sveltekitWorker);
await writeFile(
  adapterWorker,
  `// AUTO-GENERATED by scripts/merge-worker.mjs — do not edit.
// One-Worker merge (§15): SvelteKit default export + the Durable Object classes.
export { default } from "./_sveltekit_worker.js";
export { SyncDocDO, ReaderFeedDO } from "../../src/lib/server/worker-exports";
`,
);

console.log("[merge-worker] grafted SyncDocDO + ReaderFeedDO onto _worker.js");
